PRODUCTS = [
  {
    name: "Giant burger XXL",
    description: "220 g de carne de vacuno 100 % especiada, lechuga, tomate en rodajas, salsa burger, salsa mostaza dulce, pepinillos y cebolla frita crujiente, en nuestro pan XXL con semillas de sésamo",
    category: "Hamburguesas",
    price: 710,
  },
  {
    name: "Piscina",
    description: "Carne ranch gourmet (150 g), lechuga picada, tomate natural y cebolla natural, en nuestro pan con semillas de sésamo",
    category: "Hamburguesas",
    price: 520,
  },
  {
    name: "Crispy chicken",
    description: "140 g de pechuga de pollo crujiente y un toque picante, lechuga picada, tomate y salsa yogurt, en nuestro pan con semillas de sésamo",
    category: "Hamburguesas",
    price: 570,
  },
  {
    name: "Route 66",
    description: "Deliciosas tiras de carne de cerdo a la parrilla con salsa BBQ, acompañada de lechuga, en nuestro pan con semillas de sésamo",
    category: "Hamburguesas",
    price: 610,
  },
  {
    name: "Vegetal",
    description: "Hamburguesa vegetal de 120 g con lechuga y tomate, en nuestro pan con semillas de sésamo",
    category: "Hamburguesas",
    price: 570,
  },
  {
    name: "Suplementos",
    description: "Bacon, jamón york, queso, pepinillos, cebolla frita crujiente y/o huevo. El precio es por unidad",
    category: "Hamburguesas",
    price: 50,
  },
  {
    name: "Piscina",
    description: "Salchicha erik roja, salsa hot dog, salsa burger, pepinillos y cebolla frita crujiente",
    category: "Hot dogs",
    price: 470,
  },
  {
    name: "Baby",
    description: "Pan especial baby con salchicha alemana strasbourg",
    category: "Hot dogs",
    price: 220,
  },
  {
    name: "Suplementos",
    description: "Pepinillos y/o cebolla frita crujiente. El precio es por unidad",
    category: "Hot dogs",
    price: 20,
  },
  {
    name: "Bacon queso",
    description: "Pan chapata, tomate, orégano, queso y bacon",
    category: "Tosta pizzas",
    price: 420,
  },
  {
    name: "York queso",
    description: "Pan chapata, tomate, orégano, queso mozzarella y jamón york",
    category: "Tosta pizzas",
    price: 420,
  },
  {
    name: "Cuatro quesos",
    description: "Pan chapata, tomate, orégano, queso mozzarella, queso edam, queso cheddar y queso azul",
    category: "Tosta pizzas",
    price: 420,
  },
  {
    name: "Morcilla plancha",
    description: "",
    category: "Bocatas",
    price: 420,
  },
  {
    name: "Tortilla española",
    description: "",
    category: "Bocatas",
    price: 420,
  },
  {
    name: "Calamares",
    description: "",
    category: "Bocatas",
    price: 420,
  },
  {
    name: "Atún",
    description: "",
    category: "Bocatas",
    price: 420,
  },
  {
    name: "Lomo plancha",
    description: "",
    category: "Bocatas",
    price: 420,
  },
  {
    name: "Bacon",
    description: "",
    category: "Bocatas",
    price: 420,
  },
  {
    name: "Panceta",
    description: "",
    category: "Bocatas",
    price: 420,
  },
  {
    name: "Pepito ternera",
    description: "",
    category: "Bocatas",
    price: 520,
  },
  {
    name: "Chorizo plancha",
    description: "",
    category: "Bocatas",
    price: 420,
  },
  {
    name: "Pollo plancha",
    description: "",
    category: "Bocatas",
    price: 420,
  },
  {
    name: "Suplementos",
    description: "El precio es por unidad",
    category: "Bocatas",
    price: 50,
  },
  {
    name: "Montado",
    description: "Mismos tipos que bocatas excepto pepito ternera y calamares",
    category: "Bocatas",
    price: 270,
  },
  {
    name: "Sumplementos montados",
    description: "El precio es por unidad",
    category: "Bocatas",
    price: 30,
  },
  {
    name: "Mixto",
    description: "Jamón york y queso",
    category: "Sandwiches",
    price: 290,
  },
  {
    name: "Mixto con huevo",
    description: "Jamón york, queso y huevo",
    category: "Sandwiches",
    price: 370,
  },
  {
    name: "Vegetal",
    description: "Lechuga, tomate, atún, espárragos y mayonesa",
    category: "Sandwiches",
    price: 420,
  },
  {
    name: "Vegetal con pollo",
    description: "Pollo, lechuga, tomate, atún, espárragos y mayonesa",
    category: "Sandwiches",
    price: 520,
  },
  {
    name: "Salchipapas",
    description: "Salchichas nurember, bremen, brockwurst, erik y patatas",
    category: "Raciones",
    price: 920,
  },
  {
    name: "Croquetas de jamón",
    description: "",
    category: "Raciones",
    price: 870,
  },
  {
    name: "Oreja plancha",
    description: "",
    category: "Raciones",
    price: 720,
  },
  {
    name: "Tortilla española",
    description: "",
    category: "Raciones",
    price: 820,
  },
  {
    name: "Choricillos al jerez",
    description: "",
    category: "Raciones",
    price: 820,
  },
  {
    name: "Morcilla plancha",
    description: "",
    category: "Raciones",
    price: 820,
  },
  {
    name: "Panceta",
    description: "",
    category: "Raciones",
    price: 770,
  },
  {
    name: "Patatas bravas",
    description: "",
    category: "Raciones",
    price: 520,
  },
  {
    name: "Patatas ali-oli",
    description: "",
    category: "Raciones",
    price: 520,
  },
  {
    name: "Patatas mixtas",
    description: "Bravas y ali-oli",
    category: "Raciones",
    price: 520,
  },
  {
    name: "Patatas burger",
    description: "",
    category: "Raciones",
    price: 420,
  },
  {
    name: "Calamares",
    description: "",
    category: "Raciones",
    price: 870,
  },
  {
    name: "Chopitos",
    description: "",
    category: "Raciones",
    price: 920,
  },
  {
    name: "Ensalada mixta pequeña",
    description: "",
    category: "Raciones",
    price: 420,
  },
  {
    name: "Ensalada mixta grande",
    description: "",
    category: "Raciones",
    price: 620,
  },
  {
    name: "Costillar BBQ",
    description: "Acompañado con patatas fritas y salsa BBQ",
    category: "Tex mex",
    price: 1050,
  },
  {
    name: "Alitas virginia",
    description: "Alitas al estilo virginia chick'n con salsa BBQ y samurai",
    category: "",
    price: 870,
  },
  {
    name: "Nuggets de pollo",
    description: "",
    category: "Tex mex",
    price: 770,
  },
  {
    name: "Bacon-cheese fries",
    description: "Patatas fritas con mezcla de 3 quesos, bacon crispy y nuestra inconfundible crema ranch, todo ello al horno",
    category: "Tex mex",
    price: 670,
  },
  {
    name: "Sex on the beach",
    description: "",
    category: "Cocktails",
    price: 500,
  },
  {
    name: "Piña colada",
    description: "",
    category: "Cocktails",
    price: 500,
  },
  {
    name: "Mojito clásico",
    description: "",
    category: "Cocktails",
    price: 500,
  },
  {
    name: "Mojito fresa",
    description: "",
    category: "Cocktails",
    price: 500,
  },
  {
    name: "Mojito melón",
    description: "",
    category: "Cocktails",
    price: 500,
  },
  {
    name: "Zumo",
    description: "Naranja, melocotón o piña",
    category: "Bebidas",
    price: 200,
  },
  {
    name: "Batido",
    description: "Chocolate, vainilla o fresa",
    category: "Bebidas",
    price: 200,
  },
  {
    name: "Refresco",
    description: "",
    category: "Bebidas",
    price: 180,
  },
  {
    name: "Tubo cerveza",
    description: "",
    category: "Bebidas",
    price: 200,
  },
  {
    name: "Mini cerveza",
    description: "",
    category: "Bebidas",
    price: 450,
  },
  {
    name: "Combinado",
    description: "",
    category: "Bebidas",
    price: 500,
  },
  {
    name: "Mini combinado",
    description: "",
    category: "Bebidas",
    price: 1000,
  },
  {
    name: "Café",
    description: "Solo, con leche, etc.",
    category: "Bebidas",
    price: 140,
  },
  {
    name: "Licor",
    description: "",
    category: "Bebidas",
    price: 250,
  },
]

PRODUCTS.each do |product|
  Product.create(
    name: product[:name],
    description: product[:description],
    category: product[:category],
    price: product[:price],
  )
end
